version: '3'

services:

  conseiller:
    build:
      context: backoffice
    container_name: backoffice
    environment:
      - EMAIL_CONTACT=${EMAIL_CONTACT:-acme@nobody.here}
    depends_on:
      - backend
    ports:
      - 80:80
    networks:
      - mee

  candidat:
    build:
      context: front
    container_name: front
    environment:
      - DOMAINE_PATH=${DOMAINE_PATH:-HERE-URL-TO-BACKEND-ENDPOINT}
      - EMAIL_CONTACT=${EMAIL_CONTACT:-acme@nobody.here}
      - API_OFFRE_SCOPE=api_offresdemploiv2 o2dsoffre
      - API_DATE_NAISSANCE_SCOPE=datenaissance api_peconnect-datenaissancev1
      - ESD_CLIENT_ID=${ESD_CLIENT_ID:-GET-YOUR-ESD-ID}
      - ESD_CLIENT_SECRET=${ESD_CLIENT_SECRET:-GET-YOUR-ESD-SECRET}
      - API_ESD_TOKEN_ENTRYPOINT=${API_ESD_TOKEN_ENTRYPOINT:-HERE-ESD-URL-TOKEN-ENTRYPOINT}
      - API_ESD_URL=${API_ESD_URL:-HERE-ESD-URL}
      - URL_TAG_COMMANDER=${URL_TAG_COMMANDER:-HERE-TAG-COMMANDER-URL}
      - API_PE_CONNECT_SCOPE=${API_PE_CONNECT_SCOPE:-HERE-API-SCOPE}
      - URL_ACEES=${URL_ACEES:-HERE-APP-URL}
      - PE_CONNECT_IDENTITY_SERVER_URL=${PE_CONNECT_IDENTITY_SERVER_URL:-HERE-PE-CONNECT-ID-URL}
      - MAILJET_API_KEY=${MAILJET_API_KEY:-HERE-API-KEY-XXXXXXXXX}
      - MAILJET_API_SECRET_KEY=${MAILJET_API_SECRET_KEY:-HERE-API-SECRET-KEY-XXXXXXXXX}
    ports:
      - 4000:4000
    networks:
      - mee

  reverse:
    container_name: reverse
    image: nginx
    volumes:
      - ./nginx/conf/nginx.conf:/etc/nginx/nginx.conf
    ports:
      - '81:80'
    networks:
      - mee
    depends_on:
      - candidat

  backend:
    build:
      context: backend
    container_name: backend
    environment:
      - DATA_SOURCE=jdbc:postgresql://database:5432/peactions
      - DATA_SOURCE_USERNAME=peactions
      - DATA_SOURCE_PASSWORD=peactions
      - JWT_SECRET=peactionsSecretKey
      - JWT_EXPIRATION_MS=86400000
      - API_ESD_URL=${API_ESD_URL:-HERE-ESD-URL}
      - API_OFFRE_SCOPE=${API_OFFRE_SCOPE:-HERE-API-OFFRE-SCOPE}
      - API_ROME_SCOPE=${API_ROME_SCOPE:-HERE-API-ROME-SCOPE}
      - API_DATE_NAISSANCE_SCOPE=${API_DATE_NAISSANCE_SCOPE:-HERE-API-DATE-NAISS-SCOPE}
      - ESD_CLIENT_ID=${ESD_CLIENT_ID:-GET-YOUR-ESD-ID}
      - ESD_CLIENT_SECRET=${ESD_CLIENT_SECRET:-GET-YOUR-ESD-SECRET}
      - API_ESD_TOKEN_ENTRYPOINT=${API_ESD_TOKEN_ENTRYPOINT:-HERE-ESD-URL-TOKEN-ENTRYPOINT}
      - MAILJET_API_KEY=${MAILJET_API_KEY:-HERE-API-KEY-XXXXXXXXX}
      - MAILJET_API_SECRET_KEY=${MAILJET_API_SECRET_KEY:-HERE-API-SECRET-KEY-XXXXXXXXX}
      - MAILJET_ID_TEMPLATE_EMAIL_CONFIRMATION=${MAILJET_ID_TEMPLATE_EMAIL_CONFIRMATION:-01234}
      - MAILJET_ID_TEMPLATE_EMAIL_CONFIRMATION_DISTANCE_SANS_URL=${MAILJET_ID_TEMPLATE_EMAIL_CONFIRMATION_DISTANCE_SANS_URL:-01234}
      - MAILJET_ID_TEMPLATE_EMAIL_CONFIRMATION_DISTANCE_AVEC_URL=${MAILJET_ID_TEMPLATE_EMAIL_CONFIRMATION_DISTANCE_AVEC_URL:-01234}
      - MAILJET_ID_TEMPLATE_EMAIL_ANNULATION=${MAILJET_ID_TEMPLATE_EMAIL_ANNULATION:-01234}
      - MAILJET_ID_TEMPLATE_EMAIL_RAPPEL_DISTANCE=${MAILJET_ID_TEMPLATE_EMAIL_RAPPEL_DISTANCE:-01234}
      - MAILJET_ID_TEMPLATE_EMAIL_RAPPEL_PRESENTIEL=${MAILJET_ID_TEMPLATE_EMAIL_RAPPEL_PRESENTIEL:-01234}
      - MAIL_TO_REDIRECT=${MAIL_TO_REDIRECT:-acme@mail-to-redirect.test}
      - ENVIRONNEMENT_PRODUCTION=${ENVIRONNEMENT_PRODUCTION:-true}
      - REDIRECT_URI=${REDIRECT_URI:-HERE-API-REDIREC-URI}
      - CANDIDAT_ENTRYPOINT={$CANDIDAT_ENTRYPOINT:-HERE-CANDIDAT-ENTRYPOINT}
      - HIBERNATE_LOG_LEVEL=DEBUG
      - HIBERNATE_SQL_BINDER=TRACE
      - LOG_LEVEL=DEBUG
      - SITE_CANDIDAT_URL=http://localhost:4000
    depends_on:
      - flyway
    ports:
      - 8080:8080
    networks:
      - mee

  database:
    build:
      context: bdd
    container_name: database
    restart: always
    environment:
      - POSTGRES_USER=${POSTGRES_USER:-peactions}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD:-peactions}
      - POSTGRES_DB=${POSTGRES_DB:-peactions}
    ports:
      - 5400:5432
    volumes:
      - ./bdd/database:/var/lib/postgresql/data
    networks:
      - mee

  flyway:
    image: flyway/flyway:latest
    container_name: flyway
    environment:
      - FLYWAY_USER=${FLYWAY_USER:-peactions}
      - FLYWAY_PASSWORD=${FLYWAY_PASSWORD:-peactions}
      - FLYWAY_URL=jdbc:postgresql://database:5432/peactions
      - FLYWAY_SCHEMAS=public
      - FLYWAY_BASELINE_ON_MIGRATE=true
      - FLYWAY_GROUP=true
      - FLYWAY_LICENSE_KEY=community
      - FLYWAY_EDITION=community
    command: -connectRetries=60 migrate
    volumes:
      - ./bdd/sql:/flyway/sql
    networks:
      - mee
    depends_on:
      - database


volumes:
  database:

networks:
  mee:
    ipam:
      driver: default
        #config:
        #  - subnet: 172.18.1.0/24
